<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SMSL187" ignored="0" name="Realizar VC - Mobile" tests="1" failures="1" timestamp="08 oct 2019 18:23:38 GMT" time="96.481" errors="0">
  <testcase name="S_RealizarVC_01" time="65.385" classname="suiteTest.Regresion_Socio_SMS">
    <failure type="java.lang.AssertionError" message="Fallo test - S_RealizarVC_01 - Step: 09_Pantalla Agradecimiento - Visualizar">
      <![CDATA[java.lang.AssertionError: Fallo test - S_RealizarVC_01 - Step: 09_Pantalla Agradecimiento - Visualizar
	at steps.S_RealizarVC_NotificacionSMS_Step.Run(S_RealizarVC_NotificacionSMS_Step.java:87)
	at suiteTest.Regresion_Socio_SMS.S_RealizarVC_01(Regresion_Socio_SMS.java:16)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- S_RealizarVC_01 -->
</testsuite> <!-- Realizar VC - Mobile -->
